export const USER_ACTION_TYPES = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  UNSET_CURRENT_USER: "UNSET_CURRENT_USER"
};

export const FOLDER_ACTION_TYPES = {
  SET_FOLDERS: "SET_FOLDERS",
  UNSET_FOLDERS: "UNSET_FOLDERS",
  ADD_FOLDER: "ADD_FOLDER", 
  DELETE_FOLDER: "DELETE_FOLDER",
  ADD_BUTTON: "ADD_BUTTON",
  DELETE_BUTTON: "DELETE_BUTTON"
}