"""empty message

Revision ID: 84914c28f39a
Revises: 8e2580cff609
Create Date: 2022-11-27 20:04:25.198882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84914c28f39a'
down_revision = '8e2580cff609'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
